[package]
name = "backup"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
humansize = "2"
indicatif = "0.18"
json5 = "0.4"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "process", "fs", "io-util", "signal", "sync"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
tracing-tree = "0.4"
walkdir = "2"

[profile.release]
lto = "thin"
strip = true
